write output to stderr when debug is on. Dont exit script on failed policy evals
Signed-off-by: Brady Todhunter <bradyt@anchore.com>

diff --git a/lib/run_scan b/lib/run_scan
--- a/lib/run_scan
+++ b/lib/run_scan
@@ -15,46 +15,48 @@ export IMAGE_DIGEST_SHA="sha256:0a97ccb2868e3c54167317fe7a2fc58e5123290d6c5b653a
 export SCANOPTS="-r http://localhost:8228/v1 -u admin -p foobar -d ${IMAGE_DIGEST_SHA}"
 export CLIOPTS="--json"
 export ANCHORE_CI_IMAGE=${inline_scan_image_arg}
+export ANCHORE_LOG=./anchore-reports/run.log
 
 mkdir -p ./anchore-reports/
 
 if [ "${debug}" = "true" ]; then
     CLIOPTS="${CLIOPTS} --debug"
     SCANOPTS="${SCANOPTS} -V"
+    ANCHORE_LOG=/dev/stderr
     set -x
 fi
 
 # make sure the actual scan script is available
 SCAN_SCRIPT="${dirname_arg}/${scriptname_arg}"
 if [ ! -x ${SCAN_SCRIPT} ]; then
-   echo "ERROR: cannot locate executable scan script ${SCAN_SCRIPT}"
+   echo "ERROR: cannot locate executable scan script ${SCAN_SCRIPT}" >> "${ANCHORE_LOG}" 2>&1
    exit 1
 fi
 
 # make sure the image to be scanned is available and try pulling if not
-if ! docker inspect ${image_reference_arg} >> ./anchore-reports/run.log 2>&1; then
-    docker pull ${image_reference_arg} >> ./anchore-reports/run.log 2>&1
-    if ! docker inspect ${image_reference_arg} >> ./anchore-reports/run.log 2>&1; then
-        echo "ERROR: cannot locate local or remote image ${image_reference_arg}"
+if ! docker inspect ${image_reference_arg} >> "${ANCHORE_LOG}" 2>&1; then
+    docker pull ${image_reference_arg} >> "${ANCHORE_LOG}" 2>&1
+    if ! docker inspect ${image_reference_arg} >> "${ANCHORE_LOG}" 2>&1; then
+        echo "ERROR: cannot locate local or remote image ${image_reference_arg}" >> "${ANCHORE_LOG}" 2>&1
         exit 1
     fi
 fi
 
 # make sure the anchore inline scan image is available and try pulling if not
-if ! docker inspect ${inline_scan_image_arg} >> ./anchore-reports/run.log 2>&1; then
-    docker pull ${inline_scan_image_arg} >> ./anchore-reports/run.log 2>&1
-    if ! docker inspect ${inline_scan_image_arg} >> ./anchore-reports/run.log 2>&1; then
-        echo "ERROR: cannot locate local or remote image ${inline_scan_image_arg}"
+if ! docker inspect ${inline_scan_image_arg} >> "${ANCHORE_LOG}" 2>&1; then
+    docker pull ${inline_scan_image_arg} >> "${ANCHORE_LOG}" 2>&1
+    if ! docker inspect ${inline_scan_image_arg} >> "${ANCHORE_LOG}" 2>&1; then
+        echo "ERROR: cannot locate local or remote image ${inline_scan_image_arg}" >> "${ANCHORE_LOG}" 2>&1
         exit 1
     fi
 fi
 
 # start up the inline scan image
-docker run -d -p 8228:8228 --name local-anchore-engine ${inline_scan_image_arg} start >> ./anchore-reports/run.log 2>&1
-docker exec -t local-anchore-engine anchore-cli ${CLIOPTS} system wait --timeout 60 --interval 1.0 >> ./anchore-reports/run.log 2>&1
-docker cp ${anchore_policy_bundle_path_arg} local-anchore-engine:/tmp/anchore-policy-bundle.json >> ./anchore-reports/run.log 2>&1
-docker exec -t local-anchore-engine anchore-cli ${CLIOPTS} policy add /tmp/anchore-policy-bundle.json >> ./anchore-reports/run.log 2>&1
-docker exec -t local-anchore-engine anchore-cli policy activate ${anchore_policy_bundle_name_arg} >> ./anchore-reports/run.log 2>&1
+docker run -d -p 8228:8228 --name local-anchore-engine ${inline_scan_image_arg} start >> "${ANCHORE_LOG}" 2>&1
+docker exec -t local-anchore-engine anchore-cli ${CLIOPTS} system wait --timeout 60 --interval 1.0 >> "${ANCHORE_LOG}" 2>&1
+docker cp ${anchore_policy_bundle_path_arg} local-anchore-engine:/tmp/anchore-policy-bundle.json >> "${ANCHORE_LOG}" 2>&1
+docker exec -t local-anchore-engine anchore-cli ${CLIOPTS} policy add /tmp/anchore-policy-bundle.json >> "${ANCHORE_LOG}" 2>&1
+docker exec -t local-anchore-engine anchore-cli policy activate ${anchore_policy_bundle_name_arg} >> "${ANCHORE_LOG}" 2>&1
 # setup scan script CLI 
 
 # for 'scan' op
@@ -72,14 +74,16 @@ if [ ! -z "${dockerfile_path_arg}" ]; then
 fi
 
 # perform the scan callout
-${SCAN_SCRIPT} analyze ${SCANOPTS} ${image_reference_arg} >> ./anchore-reports/run.log 2>&1
+${SCAN_SCRIPT} analyze ${SCANOPTS} ${image_reference_arg} >> "${ANCHORE_LOG}" 2>&1
 export ANALYZE_RC=$?
 
 echo ""
 # docker exec -t local-anchore-engine anchore-cli image get ${IMAGE_DIGEST_SHA}
 echo "--------- Anchore Policy Evaluation ---------"
+set +eo pipefail
 docker exec -t local-anchore-engine anchore-cli evaluate check --detail ${IMAGE_DIGEST_SHA} --tag ${image_reference_arg} --policy ${anchore_policy_bundle_name_arg}
 docker exec -t local-anchore-engine anchore-cli --json evaluate check --detail ${IMAGE_DIGEST_SHA} --tag ${image_reference_arg} --policy ${anchore_policy_bundle_name_arg} > ./anchore-reports/policy_evaluation.json
+set -eo pipefail
 docker exec -t local-anchore-engine anchore-cli --json image vuln ${IMAGE_DIGEST_SHA} all > ./anchore-reports/vulnerabilities.json
 docker exec -t local-anchore-engine anchore-cli --json image content ${IMAGE_DIGEST_SHA} os > ./anchore-reports/content-os.json
 # docker exec -t local-anchore-engine anchore-cli --json image content ${IMAGE_DIGEST_SHA} java > ./anchore-reports/content-java.json
@@ -89,11 +93,11 @@ docker exec -t local-anchore-engine anchore-cli --json image content ${IMAGE_DIG
 echo ""
 
 if [ "${debug}" = "true" ]; then
+    mkdir -p ./anchore-reports/anchore-engine-logs
     docker cp local-anchore-engine:/var/log/anchore/ ./anchore-reports/anchore-engine-logs/
-    cat ./anchore-reports/run.log
 else
-    docker stop local-anchore-engine &> /dev/null
-    docker rm local-anchore-engine &> /dev/null
+    docker stop local-anchore-engine >> "${ANCHORE_LOG}" 2>&1
+    docker rm local-anchore-engine >> "${ANCHORE_LOG}" 2>&1
 fi
 
 exit ${ANALYZE_RC}
